export const testimonials = [
  {
    text: "A automação implementada pela UP Soluções transformou completamente nosso processo de vendas. Reduzimos o tempo de processamento de pedidos em 70% e praticamente eliminamos erros manuais.",
    name: "Roberto Campos",
    position: "Diretor de Operações",
    company: "TechSoft",
    initials: "RC",
    rating: 5,
  },
  {
    text: "Automatizamos nosso processo de atendimento ao cliente com a UP Soluções e o resultado foi impressionante. Nosso tempo de resposta reduziu em 85% e a satisfação dos clientes aumentou significativamente.",
    name: "Juliana Mendes",
    position: "CEO",
    company: "Conecta Serviços",
    initials: "JM",
    rating: 5,
  },
  {
    text: "A integração entre nossos sistemas que a UP Soluções implementou mudou completamente nossa operação. Agora temos uma visão unificada de todo o negócio e economizamos 20 horas semanais em tarefas manuais.",
    name: "André Silva",
    position: "Gerente de TI",
    company: "Innova Retail",
    initials: "AS",
    rating: 4,
  },
  {
    text: "Nossa estratégia de marketing foi completamente transformada com a automação implementada pela UP Soluções. Conseguimos aumentar nossa taxa de conversão em 45% e o ROI das campanhas em 60%.",
    name: "Carla Ferreira",
    position: "Diretora de Marketing",
    company: "Global E-commerce",
    initials: "CF",
    rating: 5,
  },
  {
    text: "A automação do nosso processo de gestão financeira implementada pela UP Soluções nos permitiu reduzir em 90% o tempo gasto em reconciliações bancárias e emissão de relatórios.",
    name: "Felipe Santos",
    position: "CFO",
    company: "Construções Modernas",
    initials: "FS",
    rating: 5,
  },
  {
    text: "Trabalhar com a UP Soluções foi uma experiência incrível. Eles realmente entenderam as necessidades da nossa empresa e desenvolveram uma solução de automação personalizada que nos ajudou a crescer 35% em apenas um ano.",
    name: "Mariana Barros",
    position: "COO",
    company: "Saúde Integrada",
    initials: "MB",
    rating: 5,
  },
];
